### ISSUE TITLE
WARNING: TestEngine with ID 'spek' failed to discover tests error with Spek v1.1.5 

### ISSUE THREAD

**Issue by JakeLin** [JetBrains/spek#326]
I have searched around and saw some issue like #225, #248 and #262 , they said this issue should be fixed in release `1.1.5`. However, I am still seeing this issue in Android Studio 3 like

```
Nov 10, 2017 4:49:21 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: com.xxx.SomeTest
	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:71)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:70)
	at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:79)
	at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:50)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.jetbrains.spek.tooling.runner.junit.JUnitPlatformSpekRunner.run(JUnitPlatformSpekRunner.kt:107)
	at org.jetbrains.spek.tooling.MainKt.main(Main.kt:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

These are my gradle files:

```
classpath "org.junit.platform:junit-platform-gradle-plugin:1.0.0"
```

```
testImplementation 'org.jetbrains.spek:spek-api:1.1.5'
testImplementation 'org.jetbrains.spek:spek-junit-platform-engine:1.1.5'
testImplementation 'org.junit.platform:junit-platform-runner:1.0.0'
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.0.1'
```

And test
```
@RunWith(JUnitPlatform::class)
class SomeTest : Spek({
    val x = 2
    val y = 3

    given("x = $x and y = $y") {
        val sum = x + y

        it("should be that x + y = 5") {
            Assert.assertEquals(5, sum)
        }

        it("should be that x - y = -1") {
            val subtract = x - y
            Assert.assertEquals(-1, subtract)
        }
    }
})
```

Any idea? thanks

**Comment by raniejade** [comment]
Please see this repo https://github.com/spekframework/spek-android-example. You also need a new build for the plugin https://drive.google.com/file/d/1JpUKuiXGovg0JEtGOsj9rscjQc6YNZ1b/view, which will I release once everything is good. Also, please don't use `@RunWith(...)` since the bundled JUnit plugin will take over instead of Spek's plugin.

**Comment by seanho** [comment]
+1 with the problem.

I check out the spek-android-example and try to run it with the latest Android Studio and got the same error.

**Comment by seanho** [comment]
I've tried the plugin v0.5.0 that you've provided and got this error on launch

java.lang.ClassNotFoundException: org.jetbrains.spek.idea.SpekJvmLineMarkerProvider PluginClassLoader[org.jetbrains.spek.spek-idea-plugin, 0.5.0]

**Comment by raniejade** [comment]
Can you un-install and re-install the plugin? Also, please paste the full stack trace.

**Comment by seanho** [comment]
Uninstalling and reinstalling didn't work.

I am using Android Studio 3.0 Build #AI-171.4408382 on macOS Sierra.

Here's the stack track for the "IDE Error Occurred" when I launched Android Studio.

```java
java.lang.ClassNotFoundException: org.jetbrains.spek.idea.SpekJvmLineMarkerProvider PluginClassLoader[org.jetbrains.spek.spek-idea-plugin, 0.5.0]
java.lang.RuntimeException: java.lang.ClassNotFoundException: org.jetbrains.spek.idea.SpekJvmLineMarkerProvider PluginClassLoader[org.jetbrains.spek.spek-idea-plugin, 0.5.0]
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:45)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:155)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:128)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:116)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:94)
	at com.intellij.execution.lineMarker.RunLineMarkerProvider.getLineMarkerInfo(RunLineMarkerProvider.java:54)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:186)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:111)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1156)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.spek.idea.SpekJvmLineMarkerProvider PluginClassLoader[org.jetbrains.spek.spek-idea-plugin, 0.5.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	... 28 more
```

**Comment by snowe2010** [comment]
You just need to add the launcher to your list

```
    testImplementation 'org.junit.platform:junit-platform-runner:1.0.0'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.0.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.0.0'
```

The docs should probably be updated to reflect this.

**Comment by JakeLin** [comment]
Thanks, the plugin https://drive.google.com/file/d/1JpUKuiXGovg0JEtGOsj9rscjQc6YNZ1b/view is working on this repo https://github.com/spekframework/spek-android-example.

**Comment by phatblat** [comment]
**Update:** this seems to have been a gradle caching issue as my projects are now working fine with Spek 1.1.5 and JUnit Platform 1.0.0-1.1.0. See [KotlinTemplate](https://github.com/phatblat/KotlinTemplate) for a working example.

-----
I'm also getting this error using Spek 1.1.5.

```
> Task :junitPlatformTest
Mar 15, 2018 12:16:43 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'spek' failed to discover tests
java.lang.NoClassDefFoundError: org/junit/platform/engine/discovery/ClasspathSelector
        at org.jetbrains.spek.engine.SpekTestEngine.resolveSpecs(SpekTestEngine.kt:49)
        at org.jetbrains.spek.engine.SpekTestEngine.discover(SpekTestEngine.kt:36)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
        at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.engine.discovery.ClasspathSelector
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 13 more
```

The above stacktrace indicates that the `ClassNotFoundException` is getting thrown from `
SpekTestEngine.resolveSpecs()`[ line 49](https://github.com/spekframework/spek/blob/v1.1.5/spek-junit-platform-engine/src/main/kotlin/org/jetbrains/spek/engine/SpekTestEngine.kt#L49). However, the version of that file in the `v1.1.5` tag does not reference `ClasspathSelector`, but it does reference [`ClasspathRootSelector`](https://github.com/spekframework/spek/blob/v1.1.5/spek-junit-platform-engine/src/main/kotlin/org/jetbrains/spek/engine/SpekTestEngine.kt#L23).

Since the source in the `v1.1.5` tag looks different than this stack trace, I cloned the project, checked out the tag (08208afe23b3d4cb5079a0ee85202b044b7bde11) and included Spek as a composite project (in `settings.gradle`).

```gradle
File spekProject = file("../../kotlin/spek")
if (spekProject.exists()) {
    // Composite build
    includeBuild(spekProject) {
        dependencySubstitution {
            substitute module('org.jetbrains.spek:spek-api') with project(':spek-api')
            substitute module('org.jetbrains.spek:spek-junit-platform-engine') with project(':spek-junit-platform-engine')
        }
    }
}
```

Sure enough, now Spek is working great.

```
╷
├─ JUnit Jupiter ✔
├─ Spek ✔
│  └─ org.kp.mcoe.pipeline.CalculatorSpec ✔
│     └─ given a calculator ✔
│        ├─ on addition ✔
│        │  └─ it should return the result of adding the first number to the second number ✔
│        └─ on subtraction ✔
│           └─ it should return the result of subtracting the second number from the first number ✔
└─ JUnit Vintage ✔
   ├─ org.kp.mcoe.pipeline.AssignWhitehatAppToGroupTest ✔
   │  └─ testAssignWhiteHatAppToGroup ✔
   ├─ org.kp.mcoe.pipeline.ios.managers.iOSAppManagerTest ✔
   │  └─ testXcodeBuildConfiguredForDevice ↷ Not working due to xcode plugin not being applied
```

So, it looks to me like the 1.1.5 version wasn't released from the `v1.1.5` tag.
